app:
  domain: localhost
  kind: development
  port: 3000

db:
  postgres:
    username: root
    password: root
    host: localhost
    port: 5432
    name: map-management-dev

queue:
  connection:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672