app:
  kind: production
  port: 8080

db:
  postgres:
    username: root
    password: root
    host: postgres
    port: 5432
    name: map-management

queue:
  connection:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672