app:
  kind: development
  port: 8080

db:
  postgres:
    username: root
    password: root
    host: 127.0.0.1
    port: 5432
    name: map-management-staging

queue:
  connection:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672